/**
 * =============================================================================
 * MeetScribe — Document Formatter
 * =============================================================================
 *
 * Formats structured ExtractionResult JSON into clean, readable text.
 * Used for Copy to Clipboard and Download as .txt.
 *
 * Config-driven — works for any template without code changes.
 * Reads section types from config to determine formatting (table, list, paragraph).
 *
 * Design:
 *   - Each section type has its own formatter function
 *   - Empty sections are skipped
 *   - Output is plain text optimized for email, Confluence, or document sharing
 * =============================================================================
 */

import { ExtractionResult, ExtractedSection } from '../types/extraction';

interface ColumnDef {
  key: string;
  label: string;
}

interface SectionTypeConfig {
  display: string;
  fields?: string[];
  columns?: ColumnDef[];
}

interface TemplatesConfig {
  section_types: Record<string, SectionTypeConfig>;
}

// -----------------------------------------------------------------------------
// Main Export Function
// -----------------------------------------------------------------------------

/**
 * Formats the full extraction result into a structured text document.
 *
 * @param result - The extraction result (sections array)
 * @param config - Templates config (section type definitions)
 * @param meetingName - Meeting title for the header
 * @param meetingDate - Meeting date for the header
 * @returns Formatted plain text string
 */
export function formatDocument(
  result: ExtractionResult,
  config: TemplatesConfig | null,
  meetingName?: string,
  meetingDate?: string
): string {
  const lines: string[] = [];
  const sections = result.sections || [];

  // Document Header
  lines.push('═'.repeat(60));
  lines.push(result.templateName.toUpperCase());
  if (meetingName) lines.push(meetingName);
  if (meetingDate) lines.push(meetingDate);
  lines.push('═'.repeat(60));
  lines.push('');

  // Format each section
  for (const section of sections) {
    const formatted = formatSection(section, config);
    if (formatted) {
      lines.push(formatted);
      lines.push('');
    }
  }

  // Footer
  lines.push('─'.repeat(60));
  lines.push('Generated by MeetScribe');
  lines.push('═'.repeat(60));

  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// Section Formatter — dispatches by type
// -----------------------------------------------------------------------------

function formatSection(section: ExtractedSection, config: TemplatesConfig | null): string | null {
  const data = section.data;

  // Skip empty sections
  if (!data) return null;
  if (Array.isArray(data) && data.length === 0) return null;
  if (typeof data === 'string' && data.trim() === '') return null;

  const typeConfig = config?.section_types?.[section.type] || null;
  const display = typeConfig?.display || 'bullet-list';

  const lines: string[] = [];

  // Section heading
  lines.push(section.label.toUpperCase());
  lines.push('─'.repeat(60));

  // Format content based on display type
  switch (display) {
    case 'paragraph':
      lines.push(formatParagraph(data));
      break;
    case 'bullet-list':
      lines.push(formatBulletList(data));
      break;
    case 'table':
      lines.push(formatTable(data, typeConfig?.columns || []));
      break;
    case 'numbered-list':
      lines.push(formatNumberedList(data, typeConfig?.fields || []));
      break;
    default:
      lines.push(formatBulletList(data));
  }

  return lines.join('\n');
}

// -----------------------------------------------------------------------------
// Type-specific Formatters
// -----------------------------------------------------------------------------

function formatParagraph(data: any): string {
  return String(data);
}

function formatBulletList(data: any): string {
  if (!Array.isArray(data)) return String(data);

  return data
    .filter((item: any) => item && String(item).trim())
    .map((item: any) => `  • ${String(item)}`)
    .join('\n');
}

function formatTable(data: any[], columns: ColumnDef[]): string {
  if (!Array.isArray(data) || data.length === 0) return '';
  if (columns.length === 0) return formatBulletList(data.map(d => JSON.stringify(d)));

  // Calculate column widths
  const widths: Record<string, number> = {};
  widths['#'] = 4;

  for (const col of columns) {
    const headerLen = col.label.length;
    const maxDataLen = Math.max(
      ...data.map(row => String(row[col.key] || '—').length),
      0
    );
    widths[col.key] = Math.max(headerLen, maxDataLen, 3) + 2;
  }

  const lines: string[] = [];

  // Header row
  const headerCells = [
    '#'.padEnd(widths['#']),
    ...columns.map(col => col.label.padEnd(widths[col.key]))
  ];
  lines.push(headerCells.join(''));

  // Data rows
  for (let i = 0; i < data.length; i++) {
    const row = data[i];
    const cells = [
      String(i + 1).padEnd(widths['#']),
      ...columns.map(col => String(row[col.key] || '—').padEnd(widths[col.key]))
    ];
    lines.push(cells.join(''));
  }

  return lines.join('\n');
}

function formatNumberedList(data: any[], fields: string[]): string {
  if (!Array.isArray(data) || data.length === 0) return '';

  const primaryField = fields[0] || 'title';
  const secondaryField = fields.length > 1 ? fields[1] : null;

  return data
    .map((item, idx) => {
      const primary = String(item[primaryField] || '');
      const secondary = secondaryField && item[secondaryField]
        ? `\n   ${String(item[secondaryField])}`
        : '';
      return `${idx + 1}. ${primary}${secondary}`;
    })
    .join('\n\n');
}
