

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630044504_Add_New_Table_ExportTicket') THEN
    CREATE TABLE "ExportedTickets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MeetingId" integer NOT NULL,
        "Provider" text NOT NULL,
        "Project" text NOT NULL,
        "ExternalTicketId" integer NOT NULL,
        "ExternalTicketUrl" text NOT NULL,
        "Title" text NOT NULL,
        "WorkItemType" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ExportedTickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ExportedTickets_Meetings_MeetingId" FOREIGN KEY ("MeetingId") REFERENCES "Meetings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630044504_Add_New_Table_ExportTicket') THEN
    CREATE INDEX "IX_ExportedTickets_MeetingId" ON "ExportedTickets" ("MeetingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260630044504_Add_New_Table_ExportTicket') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260630044504_Add_New_Table_ExportTicket', '8.0.0');
    END IF;
END $EF$;
COMMIT;

