

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629103455_Created_New_Table_Integration_Setting_Page') THEN
    CREATE TABLE "IntegrationSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Provider" character varying(50) NOT NULL,
        "OrganizationUrl" character varying(500) NOT NULL,
        "AccessToken" character varying(1000) NOT NULL,
        "DefaultProject" character varying(200),
        "DefaultWorkItemType" character varying(100),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_IntegrationSettings" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629103455_Created_New_Table_Integration_Setting_Page') THEN
    CREATE UNIQUE INDEX "IX_IntegrationSettings_Provider" ON "IntegrationSettings" ("Provider");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260629103455_Created_New_Table_Integration_Setting_Page') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260629103455_Created_New_Table_Integration_Setting_Page', '8.0.0');
    END IF;
END $EF$;
COMMIT;

