

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "Projects" ADD "UserId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "Meetings" ADD "UserId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "IntegrationSettings" ADD "UserId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CognitoSub" character varying(128) NOT NULL,
        "Email" character varying(256) NOT NULL,
        "Name" character varying(256) NOT NULL,
        "PictureUrl" character varying(1024),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE INDEX "IX_Projects_UserId" ON "Projects" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE INDEX "IX_Meetings_UserId" ON "Meetings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE INDEX "IX_IntegrationSettings_UserId" ON "IntegrationSettings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE UNIQUE INDEX "IX_Users_CognitoSub" ON "Users" ("CognitoSub");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    CREATE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "IntegrationSettings" ADD CONSTRAINT "FK_IntegrationSettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "Meetings" ADD CONSTRAINT "FK_Meetings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    ALTER TABLE "Projects" ADD CONSTRAINT "FK_Projects_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260702202515_User_Table_Added_And_UserId_Included_All_Tables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260702202515_User_Table_Added_And_UserId_Included_All_Tables', '8.0.0');
    END IF;
END $EF$;
COMMIT;

